CREATE DATABASE IF NOT EXISTS discussionForum;
USE discussionForum;
CREATE TABLE IF NOT EXISTS User (
    id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    passcode VARCHAR(500) NOT NULL,
    UNIQUE(id, username),
    PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS Question (
    id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(1000) NOT NULL,
    postdate DATETIME NOT NULL,
    user_id INT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(user_id) REFERENCES User(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS Answer (
    id INT NOT NULL AUTO_INCREMENT,
    answer VARCHAR(1000) NOT NULL,
    postdate DATETIME NOT NULL,
    user_id INT NOT NULL,
    question_id INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES User (id),
    FOREIGN KEY (question_id) REFERENCES Question(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS Vote(
    user_id INT NOT NULL,
    answer_id INT NOT NULL,
    isVoted BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE,
    FOREIGN KEY (answer_id) REFERENCES Answer(id) ON DELETE CASCADE
);